### ISSUE TITLE
Do we really need ability to bundle styles and js scripts inside `draft_base` theme?

### ISSUE THREAD

**Issue by vadym1930** [lemberg/draft-base-theme#5]
Hey, @lemberg/drupal-team — could be more than one opinion...
I suggest using only *.theme, templates caviars — AKA backend and theming stuff from `draft_base`, without styles and js scripts. The last ones should go from `draft_starter` theme which is a subtheme for the `draft_base`.

**Comment by OH17L** [comment]
Why?

**Comment by vadym1930** [comment]
1) Do not repeat and overlap yourselves inside `draft_starter` theme. Could be an issue...
2) Do not jump between themes for transpilling  scripts and styles and you always know where styles and scripts are living
3) One workflow direction — without decision where to drop your frontend component
